export const CHANGE_INPUT_STATUS = 'CHANGE_INPUT_STATUS';
export const CHANGE_LIST = 'CHANGE_LIST';
export const CHANGE_MOUSEIN = 'CHANGE_MOUSEIN';
export const SET_TOTALPAGE = 'SET_TOTALPAGE';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';